### ISSUE TITLE
Remove the Next/Prev buttons

### ISSUE THREAD

**Issue by nickhamze** [WordPress/wporg-theme-directory#102]
<img width="1708" alt="Screenshot 2024-05-30 at 6 19 04 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/158918/b435b9db-1491-4976-9e59-65990774c10f">

Do you have any stats on how many people actually use this feature? I wouldn't think it would be a lot of them and if they do the new design is so hidden on the bottom I don't think anyone will ever see it. I would just take them out personally.

**Comment by ryelle** [comment]
These links are here because they're on the current directory, and we're not aiming to remove any functionality right now. In the future, we could move to a "related themes" component as @StevenDufresne [suggested here](https://github.com/WordPress/wporg-theme-directory/issues/88#issuecomment-2138442798). I've moved this to a discussion here: https://github.com/WordPress/wporg-theme-directory/discussions/106
