### ISSUE TITLE
Simplify the "Commercial" and "Community" informational text.

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-theme-directory#127]
I think we can remove the `<br>` element in the Community and Commercial text. 

**Before**

|Commercial|Community|
|-|-|
|<img width="497" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/4832319/04d86b94-c7a7-4b62-8c6e-86c4e27083ed">|<img width="535" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/4832319/cb371861-9d8d-4596-a7e6-6b4e3a113628">|

**After**

|Commercial|Community|
|-|-|
|<img width="507" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/4832319/4f6bef30-7db1-410d-bc7d-8e06be0b9d30">|<img width="511" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/4832319/6c71e282-4111-41b8-964b-9f89eb212bd8">|

Thoughts @WordPress/meta-design

**Comment by StevenDufresne** [comment]
Whatever we come up with, we should share the layout with plugins:

Example: https://wordpress.org/plugins/elementor/

<img width="427" alt="Screenshot 2024-06-18 at 10 19 23 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/4be8c48f-83ba-48a3-b972-b7a167dc51ba">

**Comment by jasmussen** [comment]
Good issue, good notes @StevenDufresne. A few things: the support link on Elementors plugin page has the legacy dashicon external link. It should be the `↗`, ideally:

![Screenshot 2024-06-18 at 09 13 51](https://github.com/WordPress/wporg-theme-directory/assets/1204802/465bb7d6-88d6-42f2-a14f-5513cd9c4d8b)

As is also visible in the screenshot above, there are two support links in context of each other. The wp.org forum, and the separate commercial support link. What options do we have here? Since there's also a support forum link farther down the page, should the "Support" link be removed from the plugins page tabbar?

![Screenshot 2024-06-18 at 09 16 19](https://github.com/WordPress/wporg-theme-directory/assets/1204802/4d97f91b-8f54-40ac-b593-08575811252e)

If we did that, the sidebars between plugins and themes would move a little closer to each other already, that's a win on its own. Separately this issue would be a small win, but should "Contribute to this theme" just be "Contribute"? And can we simply copy over the text and link design from themes to plugins?

**Comment by ndiego** [comment]
I wonder if we could do something like this? 

| Commercial | Community |
|-|-|
|<img width="384" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/4832319/4a02f28a-0968-4fbe-bc00-7c7e49c8bafd">|<img width="422" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/4832319/d506a1e7-2fdf-4b43-b8c0-723933abc294">|

The wording needs some finessing, but we just include the links in the description?

**Comment by jasmussen** [comment]
That reads much better, IMO. But it's also one of those things we can refine based on any feedback that lands on this—the other wording can also work.

**Comment by ryelle** [comment]
I like the first suggestion best (just removing the line break) — it would also prevent changing out strings that translators have already translated.
