### ISSUE TITLE
Hover over theme patterns displays the default cursor instead of a pointer (hand) and there's no outline

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-theme-directory#128]
Basically, the hover states for patterns on single theme pages are not the same as the hover states for style variations, and I think they should be the same. Patterns are missing the highlighted border and the pointer cursor style. Unfortunately the screen recording tool I'm using is not picking up the different cursor styles, but you can test by looking at the T[wenty Twenty-Four page](https://wordpress.org/themes/twentytwentyfour/?new-theme=1). 

We also might want some transition applied to the animation, but I leave that to @WordPress/meta-design 

https://github.com/WordPress/wporg-theme-directory/assets/4832319/df9d0f15-a90b-41e8-8649-20b813436297

**Comment by ndiego** [comment]
Related to #126

**Comment by ryelle** [comment]
> We also might want some transition applied to the animation, but I leave that to @WordPress/meta-design

Ah, I was going to do that.

> Patterns are missing the highlighted border and the pointer cursor style.

Good catch on the cursor 👍🏻  The styles for this were only designed for the previewer, so I kind of … backported them to something that makes sense on this page. I agree the border change should be the same though, and since it was just updated in plugins, I'll go ahead and have the hover darken border color on patterns too.

**Comment by StevenDufresne** [comment]
The pattern border also appears to be thicker than the screenshot and style variations border.
<img width="320" alt="Screenshot 2024-06-18 at 10 23 18 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/47be965f-a899-4905-94c7-688d648af98f">

**Comment by jasmussen** [comment]
Good issue. A few things here, let's add a transition on both. Something a la `transition: all 0.2s ease;` does this:

![ease](https://github.com/WordPress/wporg-theme-directory/assets/1204802/b9ab5828-646d-4a77-944f-b211ccb3a370)

That's a choppy GIF but hopefully the animation comes across. For reduced motion we have this mixin in the block editor:

```
@mixin reduce-motion($property: "") {

	@if $property == "transition" {
		@media (prefers-reduced-motion: reduce) {
			transition-duration: 0s;
			transition-delay: 0s;
		}
	} @else if $property == "animation" {
		@media (prefers-reduced-motion: reduce) {
			animation-duration: 1ms;
			animation-delay: 0s;
		}
	} @else {
		@media (prefers-reduced-motion: reduce) {
			transition-duration: 0s;
			transition-delay: 0s;
			animation-duration: 1ms;
			animation-delay: 0s;
		}
	}
}
```


Steve is right about the border width, there's also something off about the radius:

![Screenshot 2024-06-18 at 08 41 26](https://github.com/WordPress/wporg-theme-directory/assets/1204802/0111a939-2756-42e2-ab91-edb1eee6763d)

It's because there's an abs-positioned element on top of a pattern preview, and the outer radius is 4px, the inner radius is 3, but it doesn't fully add up. I wonder if the border could be set on .wporg-theme-listbox .wp-block-wporg-screenshot-preview instead? It should be 4px radius, 1px width, 1.5px only on focus. Can have the same easing.

**Comment by ryelle** [comment]
Moving the issue from #139 to a comment here, it doesn't need to be a separate issue.

> This is in nit-picky territory, and it's probably related to https://github.com/WordPress/wporg-theme-directory/issues/128#issuecomment-2175270424 and how hover/focus styles are drawn on thumbnail previews. 
>
> But in case a refactor allows us to improve things, there are small edge artifacts on thumbnails. It's not immediately visible:
>
> ![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/b7c0bc37-a2ee-41ba-8687-f827ccfbdbbe)
>
> But if you zoom in, you can see the white artifacts:
>
> ![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/b9755599-b24d-4996-b00a-495ca1da32a1)
>
> This is likely from the focus style being stacked on top of a white border, using a pseudo element, rather than being drawn on the parent instead.

**Comment by ryelle** [comment]
Fixed:

- Added transition to the image scale
- Added transition to the focus/selected states
- Fixed the border radius on the pseudo-element
- Updated the cursor to pointer for hover states
- Fixed border size on unselected patterns to match 1px on style variations, and darken on hover

The white artifact is due to the white background, which is necessary for the patterns, otherwise they look like this:

<img width="283" alt="Screenshot 2024-06-18 at 4 16 27 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/48f7a119-8222-4ab6-84b6-b45fa36cd467">

And it needs to be a pseudo-element so that I can nest "borders" & have an inset border. If it's applied to the parent, it's hidden behind the image (plus the change in border width would impact the container size, so everything would shift). I know it's strange, but I did do that for a reason.

Let me know if I missed anything.

**Comment by jasmussen** [comment]
> And it needs to be a pseudo-element so that I can nest "borders" & have an inset border. If it's applied to the parent, it's hidden behind the image (plus the change in border width would impact the container size, so everything would shift). I know it's strange, but I did do that for a reason.

I'll take your word for it.

In some other contexts, we've used inset shadows to accomplish the same. If that gets paired with something like a `outline: 2px solid transparent;`, we account for Windows high contrast mode as well, which _removes_ shadows, and forcibly changes any opacities to full-opacity.
