### ISSUE TITLE
Theme page sidebar and body heading font and margin changes

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#137]
The subheadings on theme pages, both in the body content and the sidebar, could be refined. Here's how a plugin sidebar looks:

<img src="https://github.com/WordPress/wporg-theme-directory/assets/1204802/46c09721-c972-4743-ab01-417295901295" width="300">

The margin above the headings (Ratings, Support, Donate) is taller than the margin below, the font size is balanced, and the font is a sans-serif system font.

The theme directory could be the same:

<img src="https://github.com/WordPress/wporg-theme-directory/assets/1204802/18177832-631c-41f9-986c-8ebb6a2b42a7" width="300">

* 20px font size
* 50px top margin
* 20px bottom margin

The heading style for H2s in plugins is also good:

<img src="https://github.com/WordPress/wporg-theme-directory/assets/1204802/70b273dc-345a-4628-8008-694b55ff8551" width="500">

* 24px font size
* Same margin as in sidebar

That could replace the EB Garamond subheadings:

<img src="https://github.com/WordPress/wporg-theme-directory/assets/1204802/73297968-f487-47ac-b6de-f074415aa90e" width="500">

**Comment by ndiego** [comment]
Good catch ➕

**Comment by ryelle** [comment]
I've updated the default `h2` font size, font family, and font weight to match plugins, and gave headings a default top-margin of `var(--wp--preset--spacing--40)` (50px on large screens).

The headings in the sidebar now use `large` font size, and otherwise inherit the above changes.

Let me know if I missed anything from the description here.
