### ISSUE TITLE
Preview of style variations doesn't do gradients

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-theme-directory#154]
**Describe the bug**
When browsing the [new theme Creativium](https://wordpress.org/themes/creativium/) the style variations buttons only show black backgrounds

**To Reproduce**
1. Go to[ Creativium theme](https://wordpress.org/themes/creativium/)
2. Scroll to style variations
3. See the all black buttons.

**Expected behavior**
That the style variations buttons show the various variations

**Screenshots**

https://github.com/user-attachments/assets/17f2a62d-831f-4e65-b54c-05385711a8f4

**Desktop (please complete the following information):**
 - OS: Mac 14.5
 - Browser [Chrome
 - Version 126.0.6478.183

**Comment by ryelle** [comment]
The style variation cards do support gradients, as seen on Twenty Twenty-Three.

<img width="826" alt="Screenshot 2024-07-22 at 11 45 24 AM" src="https://github.com/user-attachments/assets/cebd3015-9135-4757-a255-1262673a0649">

I think the issue is that Creativium is adding the gradient in a way that isn't being applied to the card view. Twenty Twenty-Three sets [the background on the body in theme.json](https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwentythree/styles/sherbet.json#L193), while Creativium adds [a wrapper element to the page template in patterns](https://themes.trac.wordpress.org/browser/creativium/1.0.1/patterns/index.php#L9). The [card preview](https://wp-themes.com/creativium/?style_variation=amethyst+sky&card_view) expects the base color to be used as the body background.

Have you seen anything like this happen on other themes, where the style variation cards are not displayed correctly?

**Comment by bph** [comment]
[Danvatwo](https://wordpress.org/themes/danvatwo/) Seems to have a similar problem: 

https://github.com/user-attachments/assets/c19385d0-6823-4aba-b0c4-26a401ea742c

Slightly different problem with the style variation preview has [Gutenify Health Clinic](https://wordpress.org/themes/gutenify-health-clinic/)

As does [Spa Centric](https://wordpress.org/themes/spa-centric/)

**Comment by ryelle** [comment]
Danvatwo (and the parent theme, Danva) have the same problem as Creativium, it's not setting the background on the body, but is using a wrapper element.

Gutenify Health Clinic is sort of doing this? The parent theme sets the background correctly, but somehow it's not passed down to the child theme correctly - you can see how the dark theme is only half-applied to pages like this: https://wp-themes.com/gutenify-health-clinic/?page_id=2&style_variation=dark

Spa Centric uses the `background` keyword for the background color, but never actually sets that in theme.json or any of the style .json files.

I don't think we can do anything about the last two, those are theme bugs - but I'll look into what we could try for the wrapper element thing since that might be more common.

**Comment by ryelle** [comment]
I've merged a fix (https://github.com/WordPress/wordpress.org/pull/391) that should help for most of these themes. It will take some time for the cached screenshot previews to expire, I'll look into whether I can/should expire those automatically.
