### ISSUE TITLE
"Submit a theme" page

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#57]
Left align the button:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/73e974c5-5cd2-4744-ba3c-283460124fa4)

We could also improve the copy a bit, add bullets for scanability. Perhaps @thetinyl can look? A quick take:

> To ensure that WordPress users have a good experience, themes in the directory are reviewed. Please [read the guidelines before submitting](https://href.li/?https://make.wordpress.org/themes/handbook/review/).
> 
> * Themes from sites that support non-GPL themes, or themes that don’t meet the review guidelines, will not be approved.
> * Your theme will be reviewed using the [Theme Unit Test data](https://href.li/?https://codex.wordpress.org/Theme_Unit_Test). Before submitting, please test it with this sample export data.
> Further resources for theme developers can be found in the [Theme Developer Handbook](https://href.li/?https://developer.wordpress.org/themes/). For questions about theme development please use the [Themes and Templates forum](https://href.li/?https://wordpress.org/support/forum/themes-and-templates).

**Comment by thetinyl** [comment]
Thanks @jasmussen! I agree about bullets for scanability. I also noticed that the review guidelines don't specifically link to the requirements, which I think would be helpful (instead of depending on prospective theme authors to navigate to it on their own). 

Here's a suggestion based on what you've got started above:

> To ensure that WordPress users are guaranteed a good experience, every theme in the directory is reviewed by the Themes team. Your theme will have the best chance of being approved if you: 
>
> - Read the [theme review guidelines](https://make.wordpress.org/themes/handbook/review/) and follow the [submission requirements](https://make.wordpress.org/themes/handbook/review/required/). 
> - Test your theme using the [Theme Unit Test data](https://codex.wordpress.org/Theme_Unit_Test) before you upload and submit.
>
> For more theme development resources, check out the [Theme Developer Handbook](https://developer.wordpress.org/themes/). For specific questions, please use the [Themes and Templates forum](https://wordpress.org/support/forum/themes-and-templates).

A few additional copy updates I noticed in the "Getting Started" section of the page:

- Getting Started headline: Should be sentence case
- Beginning of first paragraph: capitalize "WordPress Theme Directory" --> it's a proper noun
- Beginning of last paragraph of this section: capitalize "Theme Directory"
