### ISSUE TITLE
Left align "Show all patterns"

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#66]
![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/aafe34ba-a0e1-43d3-b94b-8dd3b3054a9c)

The “Show all patterns” button could be a blue underlined link, and left-aligned:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/844e57c7-e07e-4bc8-b839-efcb8477c5c5)

**Comment by ryelle** [comment]
This is semantically a button, so it should still look like a button. Unless you'd like me to change it to a link to the preview, where all patterns are listed out? (That would also fix a performance issue I've been putting off 😅)

I can still left-align it, but since it has left-right padding, it won't be _exactly_ aligned.

| Default | Hover |
|---|---|
| <img width="348" alt="Screenshot 2024-05-13 at 11 21 13 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/fb4754bf-d2a6-46b4-beac-10a437f3a456"> | <img width="478" alt="Screenshot 2024-05-13 at 11 20 58 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/d4fd5179-5a91-481f-8cc4-d3ae3d940e79"> |

**Comment by jasmussen** [comment]
We could go with an outline button, what do you think?
