### ISSUE TITLE
Theme preview frame misaligned on mobile

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-theme-directory#84]
The bottom frame is cut off on my phone. I think because `100vh` includes the space behind the browser chrome? When scrolling down to see the bottom row, the style variations are also misaligned.

Screenshot taken using Google Pixel + Chrome:

<img src="https://github.com/WordPress/wporg-theme-directory/assets/541093/1f1177c2-95a4-4abf-8363-15a4bd7c0fe0" width="540" alt="" />

**Comment by StevenDufresne** [comment]
On some phones with pinned navigation, the controls are not reachable.

Edit: You have to swipe up in the space between the top of the phone's control and the theme itself otherwise the theme scrolls.

<img src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/af653a0c-74f5-40ab-b646-28e19479c807" width="300">

Phone: Galaxy S21
