### ISSUE TITLE
Next/Previous theme links on single page are unrelated to my query.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-theme-directory#88]
**Describe the bug**

When I search or apply filters and start looking a themes, the "next" and "previous" links on the single page are unrelated to my query. 

This works in the current theme.

**To Reproduce**
1. Search for "school" on wp.org/themes
2. Notice the first 2 items in the grid.
   - Business School
   - RT Education School 
4. Click on the first one and navigate to the bottom of the page
5. Notice that the next theme is not "RT Education School" it's "Fashion Shop". 

**Expected behavior**
The next theme should be relevant to my query.

<hr>

I feel like we had the same problem in [wporg-showcase-2022](https://github.com/WordPress/wporg-showcase-2022) but I couldn't find the issue.

**Comment by ryelle** [comment]
We discussed this on one of the calls I believe — this is just a classic WordPress limitation, a single page has no context for the query it was just in. It's the same on Showcase, though I don't remember this coming up. The pagination works by date order. We could tweak that order, but it would always be the same regardless of the previous query. 

On the call we said this was acceptable, so I'm going to close this issue.

> This works in the current theme.

Because it used Backbone to track the query, but we're using core WP functionality here.

**Comment by StevenDufresne** [comment]
Right, it wasn't on the showcase site, it was in [wporg-developer](https://github.com/WordPress/wporg-developer/pull/197#issuecomment-1414945921).... albeit a slightly different problem.

I think this is noticeably a worse experience and I'm not convinced we can use "It's how WordPress works" as a reason to close this ticket. Our mission is to help users find a relevant theme and this does the opposite by leading users randomly (relative to the user's criteria) through the theme list. We are better off having a "related themes" component than having these next/previous arrows.

**Comment by ryelle** [comment]
That seems like something we could work with design on post-launch to me, since it would be a new component. I agree it's not ideal, but in the spirit of getting the "refresh" done, I wouldn't hold on that.
