### ISSUE TITLE
Improve Single page responsivity.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-theme-directory#93]
**Describe the bug**
When viewing a single theme page at around `900px` there is a gap between the content and the image. That gap is more pronounced in themes that don't have style variations.

Can we do the following:
- Reclaim some of the margins so the sidebar isn't too narrow?
- Remove the spacing below the screenshot?

| Screenshot |
|--------|
| ![wordpress org_themes_gaming-news_](https://github.com/WordPress/wporg-theme-directory/assets/1657336/fcbe48ab-43e3-4031-ba62-7d9b7c1f41ea) | 

Theme Link:
https://wordpress.org/themes/gaming-news/

**Comment by ryelle** [comment]
> Reclaim some of the margins so the sidebar isn't too narrow?

Assuming you mean the edge-spacing left/right, no— that's global throughout the site and lines up with the global header & footer. It should break to 20px if you go a little smaller.

> Remove the spacing below the screenshot?

That's there because these are two separate column blocks, so the content actually goes: [block 1, column 1] screenshot; [block 1, column 2] buttons and meta; [block 2, column 1] description, features, etc; [block 2, column 2] ratings, support, etc.

Perhaps we could drop down to one column earlier for that first block?

![Screen Shot 2024-05-29 at 10 21 34](https://github.com/WordPress/wporg-theme-directory/assets/541093/940431aa-854f-4f0f-a83a-3a354bab5002)

**Comment by StevenDufresne** [comment]
That works for me.
