### ISSUE TITLE
Improve Pattern previews in new theme

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-theme-directory#98]
The pattern previews for themes did not change in the [new theme design](https://wordpress.org/themes/?new-theme=1), but I am wondering if we should update them to closer resemble the new [Pattern directory redesign](https://wordpress.org/patterns/). I am not sure we need as much grey border, but I like how the patterns are vertically centered in the container. 

| New theme ([Frost](https://wordpress.org/themes/frost/?new-theme=1)) | [Pattern Directory](https://wordpress.org/patterns/) |
|-|-|
|<img width="908" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/4832319/f556267f-05d6-40ad-9428-f0ef2a183979">|<img width="900" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/4832319/6ff326dd-a661-4cc1-a9cb-0fc956bd3a0b">|

**Comment by ryelle** [comment]
What do you think about this? I added the grey background because it needed something to frame it, but left the current hover effect (border change rather than background) to match the style variation cards.

<img width="847" alt="Screenshot 2024-05-30 at 5 34 03 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/806f68f5-70ab-4337-9755-bb6c2c3483b6">

_Top middle has the hover effect_

In the previewer, still cropped and centered, but smaller spacing around the images.

<img width="291" alt="Screenshot 2024-05-30 at 5 35 29 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/50d1258b-eeb6-429c-a6d9-063abfcf7f80">

**Comment by ndiego** [comment]
I love it! What do you think @WordPress/meta-design?

**Comment by jasmussen** [comment]
Sure, that works.

**Comment by fcoveram** [comment]
I like how both with the gray background and the one in the previewer. Is the dark border in hover the same as the one discussed in #96? It looks thinner to me but it could be the screenshot on my browser.

**Comment by ryelle** [comment]
The dark border is what's currently on production, I didn't change anything there. So I think it's just the screenshot, if what's on production is good.

**Comment by ryelle** [comment]
It turns out the color _is_ wrong on production, it's charcoal-5 there, but should be charcoal-1. So I'll also update that 🙂
